In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn.metrics import confusion_matrix

from sklearn.svm import LinearSVC

import warnings

warnings.filterwarnings('ignore')

In [11]:
df = pd.read_csv('data/mushrooms.csv')
df.shape

(8124, 23)

In [12]:
for column in df.columns:
    df[column] = LabelEncoder().fit_transform(df[column].values)
    
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [13]:
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
X.shape, y.shape

((8124, 22), (8124,))

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [23]:
model = LinearSVC()
model.fit(X_train, y_train)

LinearSVC()

In [16]:
y_train_pred = cross_val_predict(model, X_train, y_train, cv=3)
y_train_pred

array([0, 0, 0, ..., 0, 1, 1])

In [17]:
confusion_matrix(y_train, y_train_pred)

array([[3008,  137],
       [ 201, 2747]])

In [18]:
y_test_pred = cross_val_predict(model, X_test, y_test, cv=3)
y_test_pred

array([1, 0, 1, ..., 0, 1, 0])

In [19]:
confusion_matrix(y_test, y_test_pred)

array([[1021,   42],
       [  63,  905]])