In [36]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score


In [4]:
X = pd.read_pickle('data/new_X.p')
X.shape

(8124, 117)

In [5]:
y = pd.read_pickle('data/new_y.p')
y.shape

(8124,)

In [7]:
columns_name = pd.read_pickle('data/columns.p')

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [13]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

### Scoring for train set

In [21]:
cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy')

array([1., 1., 1.])

In [25]:
y_train_pred = cross_val_predict(model, X_train, y_train, cv=3)
y_train_pred

array([1, 1, 1, ..., 1, 0, 1])

In [28]:
confusion_matrix(y_train, y_train_pred)

array([[3176,    0],
       [   0, 2917]])

In [31]:
precision_score(y_train, y_train_pred)

1.0

In [32]:
recall_score(y_train, y_train_pred)

1.0

In [37]:
f1_score(y_train, y_train_pred)

1.0

### Scoring for test set

In [34]:
y_test_pred = cross_val_predict(model, X_test, y_test, cv=3)
y_test_pred

array([0, 1, 0, ..., 1, 0, 1])

In [35]:
confusion_matrix(y_test, y_test_pred)

array([[1032,    0],
       [   1,  998]])

In [ ]:
precision_score(y_test)